# Generated by Django 2.2.1 on 2019-08-15 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browse_record',
            fields=[
                ('browse_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True, verbose_name='菜单名称')),
                ('createby', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
            options={
                'db_table': 'sys_browse_record',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('dict_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dict_name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('dict_cont', models.CharField(max_length=255, verbose_name='分类内容')),
                ('dict_class', models.CharField(max_length=255, verbose_name='分类名称')),
                ('dict_order', models.IntegerField(null=True, verbose_name='字段顺序')),
                ('parent_id', models.CharField(max_length=255, verbose_name='pid')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否使用')),
                ('dict_type', models.IntegerField(verbose_name='字典类型')),
            ],
            options={
                'db_table': 'sys_dictionary',
            },
        ),
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('generate_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否使用')),
            ],
            options={
                'db_table': 'sys_generate',
            },
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('online_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, verbose_name='用户名')),
                ('online_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上线日期')),
            ],
            options={
                'db_table': 'sys_online',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(default=uuid.UUID('1f64310e-3c47-438c-a580-4f45628291fc'), help_text='app uuid', max_length=50, primary_key=True, serialize=False, verbose_name='app uuid')),
                ('role_name', models.CharField(max_length=30, verbose_name='角色名称')),
                ('role_menu_rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色菜单权限')),
                ('role_create_rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色新增权限')),
                ('role_delete_rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色删除权限')),
                ('role_update_rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色修改权限')),
                ('role_select_rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色查看权限')),
                ('role_order', models.CharField(max_length=30, verbose_name='角色排序')),
                ('is_active', models.IntegerField(blank=True, default=1, null=True, verbose_name='是否使用')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型名称')),
                ('img_url', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'sys_Test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名')),
                ('user_name', models.CharField(max_length=30, verbose_name='账号')),
                ('user_password', models.CharField(max_length=30, verbose_name='密码')),
                ('user_email', models.CharField(blank=True, max_length=45, null=True, verbose_name='邮箱')),
                ('user_sex', models.IntegerField(verbose_name='性别')),
                ('user_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('user_card', models.CharField(max_length=30, verbose_name='身份证号码')),
                ('createby', models.CharField(max_length=32, verbose_name='创建者')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updateby', models.CharField(max_length=32, null=True, verbose_name='更新者')),
                ('updatetime', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_active', models.IntegerField(blank=True, default=1, null=True, verbose_name='是否使用')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='头像')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmanage.Role')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('menu_url', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_order', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=60, null=True)),
                ('menu_type', models.CharField(blank=True, max_length=10, null=True)),
                ('menu_state', models.IntegerField(blank=True, null=True)),
                ('attributes_color_type', models.CharField(blank=True, max_length=30, null=True)),
                ('attributes_other', models.CharField(blank=True, max_length=100, null=True)),
                ('shiro_key', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_states', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True, verbose_name='是否使用')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sysmanage.Menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单管理',
                'verbose_name_plural': '菜单管理',
                'db_table': 'sys_menu',
            },
        ),
    ]
